# In This File We Have To Mention The Steps To How To Create Image 

FROM python:3.10-slim

WORKDIR /app

RUN pip install --no-cache-dir -r requirements.txt

COPY ..

EXPOSE 8000

CMD ["uvicorn","auth.main:app","--host","0.0.0.0","--port","8000"]